// Do not edit by hand. This file was generated by json-schema-aot.

export interface JSONSchemaDefinitions {
    [key: string]: JSONSchema;
}

/** This interface represents all of the JSON Schema functionality that is supported by this module. */
export interface JSONSchema {
    title?: string;
    description?: string;
    $schema?: string;
    $comment?: string;
    $ref?: string;
    $defs?: JSONSchemaDefinitions;
    definitions?: JSONSchemaDefinitions;
    type?: "string" | "number" | "boolean" | "object" | "array";
    pattern?: string;
    properties?: {
        [key: string]: JSONSchema;
    };
    required?: string[];
    additionalProperties?: boolean | JSONSchema;
    items?: JSONSchema;
    anyOf?: JSONSchema[];
    allOf?: JSONSchema[];
}
