/** This interface represents all of the JSON Schema functionality that is supported by this module. */
export interface JSONSchemaNode {
    type: "string" | "number" | "boolean" | "object" | "array";

    description?: string;
    pattern?: string;

    ["$schema"]?: string;
    ["$ref"]?: string;

    ["$defs"]?: {
        [key: string]: JSONSchemaNode;
    }

    properties?: {
        [key: string]: JSONSchemaNode;
    }

    required?: string[];
}

function generateRecursive(node: JSONSchemaNode, path: string[]): string {
    const errorHeader = `Unexpected type at "${path}":`;
    let code = "";

    // Check the type of this node
    const nodeType = node.type;
    const typeTestCode = (nodeType === "array") ? "!Array.isArray(json)" : `typeof(json) !== "${nodeType}"`;
    code += `if (${typeTestCode}) {
        throw \`${errorHeader} expected ${nodeType}, but encountered \${typeof(json)}\`;
    }
    `;

    switch (nodeType) {
        case "string":
        case "number":
        case "boolean":
            // Only required type checking;
            break;

        case "object":
            // TODO: Check required and possible properties
            break;
        
        case "array":
            // TODO: Check item type
            break;
    }
    
    return code;
}

export function generateValidatorCode(schema: JSONSchemaNode): string {
    let code = "// Do not edit by hand. This file was generated by json-schema-aot.\n\n"
    // TODO: Find references and create functions for them
    // TODO: Generate TypeScript type
    // TODO: Generate validator code recursively
    code += `export function validate(json) {
        ${generateRecursive(schema, ["#"])}
    }`;

    return code;
}